/*
 * drv_modbus_common.h
 *
 *  Created on: Feb 17, 2026
 *      Author: ricard
 */

#ifndef DRV_DRV_MODBUS_DRV_MODBUS_COMMON_H_
#define DRV_DRV_MODBUS_DRV_MODBUS_COMMON_H_

#define DRV_MODBUS_DEFAULT_BAUDRATE		19200
#define DRV_MODBUS_DEFAULT_PARITY		HAL_UART_PARITY_EVEN
#define DRV_MODBUS_DEFAULT_N_BITS		HAL_UART_N_BITS_8
#define DRV_MODBUS_DEFAULT_STOP_BITS	HAL_UART_STOP_BITS_1

typedef enum
{
	DRV_MODBUS_INST_0,
	DRV_MODBUS_INST_MAX
} drv_modbus_inst;

#endif /* DRV_DRV_MODBUS_DRV_MODBUS_COMMON_H_ */
