/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#include "config/config.h"
#include "hal_os/hal_os.h"
#include "hal_clk/hal_clk.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	hal_clk_init();

	hal_clk_start();

	(void)hal_clk_set_freq_hz(HAL_CLK_TARGET_FREQ_HZ);

	hal_os_init();

	hal_os_start();

	config_init_tasks();

    /* Loop forever */
	for(;;)

		hal_os_fxn();
}
